
https://demo--teambuilderapp-api.netlify.com/.netlify/functions/server/api/projects
https://teambuilderapp-api.netlify.com/.netlify/functions/server/api/projects

http://localhost:9000/.netlify/functions/server/api/users/1




